---
title: "Data Analysis and Statistics"
subtitle: ""
author: "[Andreas Handel](https://www.andreashandel.com/)"
date: "Last modified: `r file.mtime(knitr::current_input())`"
output: 
  html_document:
    toc_depth: 3
---

*Note: I have recently added more new links to the resources page of my [Modern Applied Data Analysis online course](https://andreashandel.github.io/MADAcourse/). You might want to check there (under `Resources`) for additional links to R and Data Analysis related links.*


# Other lists

* [Awesome data science](https://github.com/bulutyazilim/awesome-datascience) - Someone else's list of resources related to data science.

* [Machine learning book list](https://github.com/josephmisiti/awesome-machine-learning/blob/master/books.md) - A list of free online books concerning all things machine learning and data analysis.

* [A machine learning list of terms and definitions.](https://developers.google.com/machine-learning/glossary/)


# Online Courses for Data Analysis

* [All courses in the Data Science Specialization on Coursera](https://www.coursera.org/specializations/jhu-data-science)

* [Introduction to Statistical Learning](https://lagunita.stanford.edu/courses/HumanitiesSciences/StatLearning/Winter2016/about). 

* [Stat 545 at UBC - Data wrangling, exploration, and analysis with R](https://stat545.stat.ubc.ca/)

* [A course on deep learning using a Python stack](http://course.fast.ai)

* Check out online providers such as Coursera, edX, Udacity, etc. for more such courses

* Hadley taught a [Readings in applied data science] at Stanford [and the material is online](https://github.com/hadley/stats337) 


# Data Analysis books

* [R for Data Science](http://r4ds.had.co.nz/) - Probably the first book you should read if you plan on doing any serious data analysis in R. The focus is on the initial steps of an analysis (usually the most important ones). Not much coverage of statistical modeling. The book is freely available online.

* [Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/) - This book is your logical next step. Once you got your data cleaned and done preliminary analyses following the instructions in the previous book, this book will teach different statistical modeling/analysis approaches. Also R based and freely available online.

* [Elements of Statistical Learning](http://statweb.stanford.edu/~tibs/ElemStatLearn/) - This is the more advanced version by some of the same authors of the previous book. It gets technical, so only suitable once you got the basics figured out.

* [Introduction to Data Science](http://jsresearch.net/index.html)

* [Deep Learning book](http://www.deeplearningbook.org/)

* [Stat 545](https://stat545.com/) - Jenny Bryan's book based on her previous teaching of a course by that name (see above)


# Online tutorials

* [A Computerworld tutorial on data wrangling](http://www.computerworld.com/s/article/9243391/4_data_wrangling_tasks_in_R_for_advanced_beginners)



# Useful data-analysis related R packages

* [Caret](http://topepo.github.io/caret/index.html) - a package that allows many different modeling approaches from a single interface

* [Machine Learning in R - mlR](https://github.com/mlr-org/mlr) - similar concept as Caret but different strengths and weaknesses. I would check out both.

*  [Collection of R packages for dealing with data](http://www.computerworld.com/article/2921176/business-intelligence/great-r-packages-for-data-import-wrangling-visualization.html)

* [The tidyverse](http://tidyverse.org/) - Hadley Wickham & Co's packages for all things data analysis.


# Random stuff

* [A nice cartoon-supported illustration of Hill's criteria for causality, applied to Data analysis](http://livefreeordichotomize.com/2016/12/15/hill-for-the-data-scientist-an-xkcd-story/)


# Specific Topics

## Data cleaning and checking

* Check out the R packages tidyr, plyr, dplyr, validate, vtreat (you can find good documentation for all of them)

* [Data Analysis and Visualization Using R](http://varianceexplained.org/RData/)

* [A nice series of blog posts describing common data manipulations for dplyr](https://suzan.rbind.io/2018/01/dplyr-tutorial-1/)


## Visualization

* [R Graph Gallery](http://www.r-graph-gallery.com/): Has lots of examples of graphs and plots in R, including the underlying code that produced the graph. Great place to find a graph similar to one you'd like to make, take the code and adjust it.

* [This website](http://www.sthda.com/english/wiki/ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page) has a nice article describing ways to create different multi-panel plots.


## Missing Data/Imputation

* Check out R packages mi, mice, Amelia, missforest, imputation

* Little & Rubin "Statistical Analysis with Missing Data, 2nd Edition"


## Bayesian Analysis

* The [Statistical Rethinking book](https://xcelab.net/rm/statistical-rethinking/)

* [Lecture notes from Mark Lai's class](https://bookdown.org/marklhc/notes_bookdown/)

* [brms package site](https://github.com/paul-buerkner/brms)


## p-values

* [Nice discussion of p-values](http://fivethirtyeight.com/features/not-even-scientists-can-easily-explain-p-values/)

* [Another stab at p-values](http://fivethirtyeight.com/features/statisticians-found-one-thing-they-can-agree-on-its-time-to-stop-misusing-p-values/)

* [Great example explaining what p-values do and don't mean](http://livefreeordichotomize.com/2017/08/14/why-you-maybe-shouldnt-care-about-that-p-value/)

* [Another good discussion of the problem with p-values](https://emcrit.org/pulmcrit/p-value-cutoffs/)


## Epidemiology specific topics

* [tableone](https://cran.r-project.org/package=tableone) - A package that allows for convenient creation of a descriptive table based on a data frame.

* [compareGroups](https://cran.r-project.org/package=compareGroups) - A package that allows for convenient creation of result tables from linear and logistic (and related) models.

* The [R survival package](https://cran.r-project.org/web/packages/survival/index.html) - Lots of functionality for survival analysis.

## Time-series analysis

* The [R survival package](https://cran.r-project.org/web/packages/survival/index.html) - Lots of functionality for survival analysis.

* [Forecasting: principles and practice](https://otexts.com/fpp2/)
