---
title: "R Programming"
subtitle: ""
author: "[Andreas Handel](https://www.andreashandel.com/)"
date: "Last modified: `r file.mtime(knitr::current_input())`"
output: 
  html_document:
    toc_depth: 3
---

*Note: I have recently added more new links to the resources page of my [Modern Applied Data Analysis online course](https://andreashandel.github.io/MADAcourse/). You might want to check there (under `Resources`) for additional links to R and Data Analysis related links.*


# Lists by others

* [A list of _the best_ R tools] (https://github.com/qinwf/awesome-R)


# Online Courses for R

* [Swirl](http://swirlstats.com/) - An R package that teaches R interactively inside R. Not as polished as DataCamp, but good interactivity, great motivating feedback/messages, beginner and intermediate levels. Completely free.

* [Try R, a free course at codeschool.com](https://www.codeschool.com/courses/try-r)


# R books and tutorials

* [YaRrr! The Pirate's Guide to R:](http://nathanieldphillips.com/thepiratesguidetor/) A nice R introduction with a piratey bend

* [Computerworld's R beginner guide](http://www.computerworld.com/s/article/9239625/Beginner\_s\_guide\_to\_R\_Introduction) 

* ['R Meta book' - a list of resources on specific topics:](https://www.r-bloggers.com/an-r-meta-book/)

* [Springer has a series of books called 'Use R'](http://www.springer.com/series/6991) - A long and growing series of books on a lot of different R topics. From beginner to advanced. Many university libraries have a subscription to Springer Online, which allows you to get the books for free.

* Roger Peng's ["R programming for data science"](https://leanpub.com/rprogramming) book on Leanpub. Name your own price.	
	
* ["Advanced R" by Hadley Wickham for more advanced R coding](http://adv-r.had.co.nz/)


# General R Online Resources

* [Quick R](http://www.statmethods.net/) - a great resource for many 'how do I' questions of common data analysis and graphics tasks. 

* [Cookbook for R](http://www.cookbook-r.com/) - another useful collection of 'how do I do X' information.

* [R bloggers](https://www.r-bloggers.com/) an aggregation of blogs about all things R

* [Convenient reference/cheat sheets for some important R tasks](https://www.rstudio.com/resources/cheatsheets/)

* [Resource collection to do useful data analysis related tasks in R](http://rddj.info/)

*  [R Documentation:](https://www.rdocumentation.org/) - a webpage and R package that tries to enhance the help/documentation files for R and its packages.

* [The Task View sorting R packages into categories is often useful](http://cran.r-project.org/web/views/)


	
# R and Shiny

* [Official shiny webpage](http://shiny.rstudio.com/)
* [Collection of Shiny tips and tricks](https://github.com/daattali/advanced-shiny), [see also here](https://deanattali.com/blog/advanced-shiny-tips/
) and [here](https://shiny.rstudio.com/articles/dynamic-ui.html)
* [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/)
* [Outstanding User Interfaces with Shiny](https://unleash-shiny.rinterface.com/) - a book covering advanced Shiny material, covering advanced styling, mobile development, integration with other web technologies, etc.



# R Markdown and related
* [Collection of R Markdown Tips and Tricks](https://indrajeetpatil.github.io/RmarkdownTips/)


# R package development

* ["R packages" by Hadley Wickham](http://r-pkgs.had.co.nz/). This (free online) book alone is enough to get a package done. Should definitely be the first (and maybe even only) source to read/use.
* [How to quickly write an R package](http://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/)
* [A series of online videos talking about package development](https://youtu.be/79s3z0gIuFU)
* `devtools`, `roxygen2`, etc. - almost required for development. See Hadley's book.
* `available` - tests if a specific name is still available
* `usethis` - helps with a lot of setup tasks for packages (and other R coding tasks)


